Serve default file when no file matches
restify/plugins pull request #31
Opened 2016-05-18 07:06 UTC by JoeDoyle23

I ran into the same issue as #13 and was expecting the serveStatic plugin to server the default file if there wasn't a match in the file system, which is what the documentation implies.

This PR inserts a check to see if a default file was specified and to try and serve that instead of returning ResourceNotFound. There is also a check to make sure that we do send ResourceNotFound is the default file doesn't exist. This makes the serveStatic plugin match what the documentation describes.

2016-05-18 17:59 UTC, micahr commented on lib/plugins/static.js
> +            var defaultFile = path.join(opts.directory, opts.default);
Can you add `opts.default` to the assertion block at the top to ensure we get a proper format for the input?

2016-05-18 20:20 UTC, JoeDoyle23 commented on lib/plugins/static.js
> +            var defaultFile = path.join(opts.directory, opts.default);
Done. Let me know if there's anything else

2016-10-27 16:58 UTC, yunong requested changes

2016-10-27 16:58 UTC, yunong commented on lib/plugins/static.js
> +            var defaultFile = path.join(opts.directory, opts.default);
Hey @JoeDoyle23 Thanks for this submission, and apologies for the late reply. Would you mind adding a unit test for this behaviour? We should be good to merge after that.

2017-05-09 20:40 UTC, retrohacker commented
Hey @JoeDoyle23,

We appreciate this PR! :heart:

It looks like this is in the home stretch for being merged, just pending tests. We are in the process of moving the plugins back into the main repo. If memory serves, we directed you here in the first place, sorry to send you back and forth. I'm going to close this PR for now so we can get the merge underway (it is one of the few things left blocking a 5.x release). If this PR is still important to you, please re-open it against the main repo with tests and we will be more than happy to merge :smile:

2017-05-09 20:40 UTC, closed without merging