added partial support for client initiated content encoding (RFC 7694)
restify/plugins pull request #70
Opened 2016-11-03 09:00 UTC by vstirbu

This PR implements partial support for [RFC 7694 Hypertext Transfer Protocol (HTTP) Client-Initiated Content-Encoding](https://tools.ietf.org/html/rfc7694), more specifically this interaction:

>    A client submits a POST request using the "compress" content coding
>    ([RFC7231], Section 3.1.2.1):
> 
>      POST /edit/ HTTP/1.1
>      Host: example.org
>      Content-Type: application/atom+xml;type=entry
>      Content-Encoding: compress
> 
>      ...compressed payload...
> 
>    The server rejects the request because it only allows the "gzip"
>    content coding:
> 
>      HTTP/1.1 415 Unsupported Media Type
>      Date: Fri, 09 May 2014 11:43:53 GMT
>      Accept-Encoding: gzip
>      Content-Length: 68
>      Content-Type: text/plain
> 
>      This resource only supports the "gzip" content coding in requests.

I have looked for `bodyReader` tests but could not find them.

2016-11-05 03:28 UTC, DonutEspresso commented
Hello, thank you for the pull request! Indeed, it looks like we are missing a bodyReader test. 

Would you mind adding a new bodyReader test file? Feel free to add only the tests relevant for the this PR - we'll follow up and add more tests.

2016-11-06 20:49 UTC, vstirbu commented
bodyReader tests added.

2017-05-09 22:59 UTC, retrohacker requested changes

2017-05-09 22:59 UTC, retrohacker commented on lib/plugins/bodyReader.js
> +                next(new UnsupportedMediaTypeError('Unsupported compression type ' + unsupportedCompression));
I believe this needs to be followed by a `return` to abort execution

2017-05-09 23:03 UTC, retrohacker commented on test/bodyReader.js
> +
Extra whitespace (we should be linting this)

2017-05-09 23:03 UTC, retrohacker commented on test/bodyReader.js
> +
Extra whitespace (we should be linting this)

2017-05-09 23:34 UTC, retrohacker commented
Closing in favor of #70 

Commit history preserved

2017-05-09 23:34 UTC, closed without merging