add reqQueueDepth plugin
restify/plugins pull request #77
Opened 2016-12-13 04:17 UTC by DonutEspresso

2016-12-13 04:22 UTC, yunong requested changes

2016-12-13 04:22 UTC, yunong commented on lib/pre/reqQueueDepth.js
> +        // for when client (or Zuul) kills the request, or gives up prematurely
What is Zuul? I think client is sufficient for those who have no Netflix specific knowledge

2016-12-13 04:22 UTC, yunong commented on lib/pre/reqQueueDepth.js
> +        res.once('close', _pop);
Will this catch an uncaught exception caught by a domain?

2016-12-13 04:22 UTC, yunong commented on test/reqQueueDepth.js
> +    it('should throw when missing server argument', function (done) {
I'd add a few more tests that simulate what happens on 404s, or uncaughtExceptions, or timeouts.

2016-12-13 04:22 UTC, yunong commented on lib/pre/reqQueueDepth.js
> +            QUEUE_LENGTH -= 1;
You should probably add an assert here and log a warn, if QUEUE_LENGTH is ever potentially < 0, that means there's a bug somewhere, probably best to keep length at 0 and not go negative.

2016-12-13 04:24 UTC, DonutEspresso commented on lib/pre/reqQueueDepth.js
> +        res.once('close', _pop);
Nope, uncaughts are unaffected.

2016-12-13 04:28 UTC, yunong commented on lib/pre/reqQueueDepth.js
> +        res.once('close', _pop);
doesn't this mean you'll be "leaking" the queue count. If you're incrementing but never decrementing cus u have uncaughts, this will keep going up?

2016-12-13 04:52 UTC, DonutEspresso commented on lib/pre/reqQueueDepth.js
> +            QUEUE_LENGTH -= 1;
Added

2016-12-13 05:06 UTC, DonutEspresso commented on lib/pre/reqQueueDepth.js
> +        res.once('close', _pop);
Test added

2016-12-13 05:06 UTC, DonutEspresso commented on test/reqQueueDepth.js
> +    it('should throw when missing server argument', function (done) {
Tests added

2016-12-13 05:09 UTC, DonutEspresso commented
I think that covers most of the comments, can you take another look?

2016-12-13 05:18 UTC, yunong commented
Can you add docs to readme? Everything else looks good.

2016-12-13 19:06 UTC, micahr approved these changes

2016-12-13 20:12 UTC, rajatkumar approved these changes
LGTM

2016-12-13 20:39 UTC, DonutEspresso commented
Going to rejigger this PR to use the 'after 'event if possible.

2016-12-15 03:01 UTC, DonutEspresso commented
Closing in favor of restify/node-restify#1250

2016-12-15 03:01 UTC, closed without merging