create metrics after plugin
restify/plugins pull request #78
Opened 2016-12-15 21:53 UTC by DonutEspresso

2016-12-15 22:27 UTC, DonutEspresso commented
CI will fail until restify/node-restify#1251 lands

2016-12-15 22:54 UTC, yunong requested changes
A few documentation bugs. Overall looks good.

2016-12-15 22:54 UTC, yunong commented on README.md
> +  * `metrics.connectionState` {String} can be either 'closed' or 'aborted'. If
s/closed/close

2016-12-15 22:54 UTC, yunong commented on lib/plugins/metrics.js
> +            // 'close' | 'aborted'
or null

2016-12-15 22:54 UTC, yunong commented on test/metrics.test.js
> +describe('query parser', function () {
query parser?

2016-12-15 22:57 UTC, DonutEspresso commented
Comments addressed, one last time?

2016-12-15 23:01 UTC, yunong commented on lib/plugins/metrics.js
> +            // 'close' | 'aborted'
Still haven't updated this in the docs?

2016-12-15 23:02 UTC, yunong commented on lib/plugins/metrics.js
> +            // 'close' | 'aborted'
e.g. close | aborted | null

2016-12-15 23:02 UTC, yunong commented on lib/plugins/metrics.js
> +            statusCode: res.statusCode,
probably best to add a comment here about this being null too, and how it gets here.

2016-12-15 23:13 UTC, DonutEspresso commented on lib/plugins/metrics.js
> +            // 'close' | 'aborted'
Oh shoot, updated the README didn't update this. Default value is undefined

2016-12-15 23:43 UTC, DonutEspresso commented
Third time's the charm?

2016-12-16 00:17 UTC, yunong approved these changes

2016-12-16 01:11 UTC, merged